linters:
  enable-all: false
  enable:
    # Enabled By Default Linters
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    # add
    - misspell
    - revive
    - stylecheck
    - gosec
    - lll
    - goconst
    - gocritic
  disable-all: true
