AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 5

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
      - arm64
      Events:
        hello:
          Type: HttpApi
          Properties:
            Path: /hello
            Method: GET
        create:
          Type: HttpApi
          Properties:
            Path: /create
            Method: POST
      Environment:
        Variables:
          TABLE_NAME: test-rate-limit
          RATE_LIMIT: 20
          BUCKET_SIZE: 40
          INTERVAL: 60
      Policies:
      - Statement:
        - Sid: DynamoDBAccess
          Effect: Allow
          Action:
          - dynamodb:BatchWriteItem
          - dynamodb:GetItem
          - dynamodb:UpdateItem
          Resource: '*'
    Metadata:
      DockerTag: go1.x-v1
      DockerContext: ./
      Dockerfile: Dockerfile
