AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 5

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        hello:
          Type: HttpApi
          Properties:
            Path: /hello
            Method: GET
        create:
          Type: HttpApi
          Properties:
            Path: /create
            Method: POST
      Environment:
        Variables:
          PARAM1: VALUE
    Metadata:
      DockerTag: go1.x-v1
      DockerContext: ./app
      Dockerfile: Dockerfile

